# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  高性能服务架构 v1.0.0 | 沉淀、分享、成长，让自己和他人都能有所收获
subtitle: 沉淀、分享、成长，让自己和他人都能有所收获
name: 高性能服务架构
email: wchuanc@126.com
description: 沉淀、分享、成长，专注于原创专题案例，以最易学习编程的方式分享知识，让自己和他人都能有所收获。目前已完成的专题有；Netty4.x实战专题案例、用Java实现JVM、基于JavaAgent的全链路监控、手写RPC框架、DDD专题案例等。
keywords: C++,Linux,服务架构,音视频,全栈，程序人生
encoding: "utf-8"
favicon: favicon.ico 

repository: wangchuanchuan/wangchuanchuan.github.io
github_url: https://github.com/wangchuanchuan
url: https://wchuanc.cn
enforce_ssl: wchuanc.cn

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list 导航 顶部菜单列表
menus:

  -
    href: /open-source.html
    label: Git
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self


# Navigation. main menu list
navs:

  -
    href: /
    label: 首页

  - href: /
    label: C/C++/GO
    target: _self
    subnav:
      - subHref: /itstack-demo-any/itstack-demo-any.html
        subLabel: 编程基础
      - subHref: /itstack-demo-algorithm/itstack-demo-algorithm.html
        subLabel: 算法与数据结构
      - subHref: /itstack-demo-springcloud/itstack-demo-springcloud.html
        subLabel: C++ 11
      - subHref: /itstack-demo-jvm/itstack-demo-jvm.html
        subLabel: 用Java实现JVM
      - subHref: /itstack-demo-drools/itstack-demo-drools.html
        subLabel: Golang DevOps项目
  -
    href: /itstack-demo-netty/itstack-demo-netty.html
    label: Linux后台工程师专题
    target: _self
    subnav:
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-1.html
        subLabel: 算法设计专题
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-2.html
        subLabel: 后台组件编程
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-3.html
        subLabel: 代码工程优化
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-4.html
        subLabel: 网络服务专题
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-4.html
        subLabel: 开源框架专题
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-4.html
        subLabel: 性能测试专题
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-4.html
        subLabel: Linux系统专题
      -
        subHref: /itstack-demo-netty/itstack-demo-netty-4.html
        subLabel: 互联网云盘实战

  -
    href: /
    label: Linux高级互联网架构师
    target: _self
    subnav:
      -
        subHref: /itstack-ark-middleware/itstack-ark-middleware.html
        subLabel: 源码分析专题
      -
        subHref: /itstack-demo-agent/itstack-demo-agent.html
        subLabel: 中间件开发专题
      -
        subHref: /itstack-demo-ddd/itstack-demo-ddd.html
        subLabel: 集群开发专题
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 性能测试专题
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 运维统计专题
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 分布式架构专题
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: IM实时流媒体实战
        -
        
    href: /
    label: 挑战网络性能极限DPDK专栏
    target: _self
    subnav:
      -
        subHref: /itstack-ark-middleware/itstack-ark-middleware.html
        subLabel: 认知DPDK
      -
        subHref: /itstack-demo-agent/itstack-demo-agent.html
        subLabel: Cache和内存
      -
        subHref: /itstack-demo-ddd/itstack-demo-ddd.html
        subLabel: 并行计算
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 同步互斥机制
        -
    href: /
    label: 全方位分析Linux内核
    target: _self
    subnav:
      -
        subHref: /itstack-ark-middleware/itstack-ark-middleware.html
        subLabel: 进程管理和调度
      -
        subHref: /itstack-demo-agent/itstack-demo-agent.html
        subLabel: 内存管理
      -
        subHref: /itstack-demo-ddd/itstack-demo-ddd.html
        subLabel: 进程虚拟内存
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 设备驱动程序
      -
        subHref: /itstack-demo-ddd/itstack-demo-ddd.html
        subLabel: 系统调用
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 页面回收和页面交互
        href: /
    label: 音视频技术专题
    target: _self
    subnav:
      -
        subHref: /itstack-ark-middleware/itstack-ark-middleware.html
        subLabel: 音视频基础入门
      -
        subHref: /itstack-demo-agent/itstack-demo-agent.html
        subLabel: FFMPEG命令实战
      -
        subHref: /itstack-demo-ddd/itstack-demo-ddd.html
        subLabel: FFMPEG编程实战
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: 流媒体实战
      -
        subHref: /itstack-demo-frame/itstack-demo-frame.html
        subLabel: WEBRTC实战

  -
    href: /archives.html
    label: Archives
    target: _self

# labels. my blog key words
labels:

  -
    href: /open-source.html
    label: Git仓库
    target: _blank
  -
    href: /gitchat.html
    label: GitChat
    target: _blank

# selected articles 精选文章
classes:

  -
    href: /itstack-demo-netty/itstack-demo-netty.html
    name: IM实时流媒体案例
    describe: 跟着案例学Netty，Netty4.x案例从简单入门到应用实战，全篇35节优秀案例+实战源码[基础篇(13)、中级篇(13)、高级篇(3章+)、源码分析篇]。

  -
    href: /itstack-demo-jvm/itstack-demo-jvm.html
    name: Janus服务源码分析
    describe: 本专题通过Java代码来实现JVM的基础功能（搜索解析class文件、字节码命令、运行时数据区等），从而让java程序员通过最熟知的java程序，学习JVM是如何将java程序一步步跑起来的。

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: wangchuanchuan
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: wangchuanchuan
  repo: wangchuanchuan.github.io
  oauth:
    client_id: df8beab2190bec20352a
    client_secret: 7eeeb4369d699c933f02a026ae8bb1e2a9c80e90
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: wangchuanchuan
  repo: wangchuanchuan.github.io
  clientID: df8beab2190bec20352a
  clientSecret: 7eeeb4369d699c933f02a026ae8bb1e2a9c80e90
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
